### PR TITLE
Create tea.yaml

### PR DESCRIPTION
**Pull request by emmysub**
emmysubn from tea

### CODE REVIEW

**Comment by emmysub** [comment]
please accept and merge my file so as to enable me complete my project, thanks.

**Comment by neojski** [comment]
Can you explain what the change is supposed to be doing?

**Comment by neojski** [comment]
I think you're trying to register my project as an owner in the tea protocol, whatever that is. This seems wrong to me so I'm going to reject this PR.

**Comment by emmysub** [comment]
Hi good afternoon,

I just saw your mail
Please not that I want to register it as the owner I'm just performing some
testnet task please approve it I plead. Thanks as I wait to here ur kind
response, I appreciate.

**Pull request closed without merging**
